# Generated by Django 3.2.8 on 2022-11-13 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='apellidos',
        ),
    ]
