# Generated by Django 3.2.8 on 2022-11-13 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_remove_usuarios_apellidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='apellidos',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Apellidos'),
        ),
    ]
