# Generated by Django 3.2.8 on 2022-11-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fruits', '0002_remove_fruits_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruits',
            name='imagen',
            field=models.ImageField(null=True, upload_to='Images', verbose_name='Imagen'),
        ),
    ]
