# Generated by Django 3.2.8 on 2022-11-13 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fruits', '0004_remove_fruits_imagen'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fruits',
            new_name='FruitsModel',
        ),
    ]
